name: flutter_application_alya
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo_ypc.png
    - images/propil.png
    - images/fto1.jpg
    - images/fto2.jpg
    - images/fto3.jpg
